version: '3.7'
services:
  db:
    image: postgres:13-alpine  
    container_name: employee-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - employee-network     
  application:
    container_name: employee-application
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
       - ./data:/home
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - fileName=./home/employees.txt
    networks:
      - employee-network
    depends_on:
      - "db"
networks:
  employee-network:
    name: employee-network
    driver: bridge

